stages:
  - build_and_deploy

# Define a step 'build & deploy'
build_and_deploy:
  # step is part of stage 'build'
  stage: build_and_deploy
  rules:
    - if: $CI_COMMIT_TAG =~ /\d+\.\d+\.\d+(-\\w+)?/
  artifacts:
    paths:
      - dist
  image: node:latest

  script:
    - git checkout -b $CI_COMMIT_TAG
    - npm install
    - npm version --commit-hooks false --git-tag-version false $CI_COMMIT_TAG
    - npm run build-gslib
    - npm run build
    - apt-get update && apt-get install sshpass --assume-yes
    - sshpass -p $KISPACE_ROOT_PWD scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r ./dist/* root@kispace.de:/var/www/geo.kispace.de/$CI_COMMIT_TAG/
    - sshpass -p $KISPACE_ROOT_PWD ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@kispace.de "ln -sfn /var/www/geo.kispace.de/$CI_COMMIT_TAG /var/www/geo.kispace.de/latest ; exit"



  allow_failure: false
