name: Auto Tag on Version Commit

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  auto-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Extract version and create tag
        run: |
          # Get the commit message
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "Commit message: $COMMIT_MSG"
          
          # Extract version pattern (v0.12.9, v1.2.3, etc.)
          VERSION_WITH_V=$(echo "$COMMIT_MSG" | grep -oE 'v[0-9]+\.[0-9]+\.[0-9]+' | head -n 1)
          
          if [ -n "$VERSION_WITH_V" ]; then
            # Strip the 'v' prefix to get semantic version
            VERSION=${VERSION_WITH_V#v}
            echo "Found version in commit: $VERSION_WITH_V"
            echo "Creating tag: $VERSION"
            
            # Check if tag already exists
            if git rev-parse "$VERSION" >/dev/null 2>&1; then
              echo "Error: Tag $VERSION already exists!"
              exit 1
            fi
            
            # Create and push the tag (without 'v' prefix)
            git tag "$VERSION"
            git push origin "$VERSION"
            echo "Created and pushed tag: $VERSION"
            echo "This will trigger the build-and-deploy workflow"
          else
            echo "No version pattern found in commit message"
          fi

