name: Reusable Test Workflow

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node.js version to use'
        required: false
        type: string
        default: '20'
      run-coverage:
        description: 'Whether to run coverage'
        required: false
        type: boolean
        default: true
      coverage-flags:
        description: 'Coverage flags for codecov'
        required: false
        type: string
        default: 'unittests'
      coverage-name:
        description: 'Coverage name for codecov'
        required: false
        type: string
        default: 'codecov-umbrella'
      continue-on-test-error:
        description: 'Continue on test errors'
        required: false
        type: boolean
        default: true
    outputs:
      test-result:
        description: 'Result of the test job'
        value: ${{ jobs.test.outputs.result }}
      coverage-result:
        description: 'Result of the coverage job'
        value: ${{ jobs.coverage.outputs.result }}

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.test-status.outcome }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint --if-present

      - name: Run type checking
        run: npx tsc --noEmit

      - name: Run unit tests
        id: test-status
        run: npm run test:run
        continue-on-error: ${{ inputs.continue-on-test-error }}

  coverage:
    runs-on: ubuntu-latest
    needs: test
    if: inputs.run-coverage
    outputs:
      result: ${{ steps.coverage-status.outcome }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        id: coverage-status
        run: npm run test:coverage
        continue-on-error: ${{ inputs.continue-on-test-error }}

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/lcov.info
          flags: ${{ inputs.coverage-flags }}
          name: ${{ inputs.coverage-name }}
          fail_ci_if_error: false
